plugin: community.general.proxmox
url: "{{ lookup('ansible.builtin.env', 'proxmox_url') }}"
user: "{{ lookup('ansible.builtin.env', 'proxmox_admin_username') }}"
# password: "{{ lookup('ansible.builtin.env', 'proxmox_admin_password') }}"
validate_certs: "{{ not lookup('ansible.builtin.env', 'proxmox_tls_insecure') }}"
token_id: "{{ lookup('ansible.builtin.env', 'proxmox_api_token_id_short') }}"
token_secret: "{{ lookup('ansible.builtin.env', 'proxmox_api_token_secret') }}"

want_facts: true
exclude_nodes: true
keyed_groups:
    # proxmox_tags_parsed is only returned when 'want_facts=true'
  - key: proxmox_tags_parsed
    separator: ""
    prefix: group
groups:
  linux: "'ubuntu' in (proxmox_tags_parsed|list)"
  test: "'test' in (proxmox_tags_parsed|list)"
filters:
  - proxmox_name | regex_search('^prod-')
